name: 通过 Maven 部署 Java

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 建立 JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          cache: 'maven'

      - name: 通过 Maven 编译
        run: mvn -B package --file pom.xml && mkdir staging && cp target/*.jar staging

      - name: 上传编译构件
        uses: actions/upload-artifact@v3
        with:
          name: 编译结果
          path: staging